-- MySQL Script generated by MySQL Workbench
-- Sat Sep 24 19:32:17 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema spruce_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema spruce_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spruce_db` DEFAULT CHARACTER SET utf8 ;
USE `spruce_db` ;

-- -----------------------------------------------------
-- Table `spruce_db`.`user_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spruce_db`.`user_types` (
  `id` INT NOT NULL,
  `role` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spruce_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spruce_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `birthday` DATE NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `join_date` TIMESTAMP NULL,
  `is_ban` TINYINT NULL,
  `profile_img` VARCHAR(255) NULL,
  `code` INT NULL,
  `user_type_id` INT NOT NULL,
  `jwt` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_user_types1_idx` (`user_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_user_types1`
    FOREIGN KEY (`user_type_id`)
    REFERENCES `spruce_db`.`user_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spruce_db`.`discounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spruce_db`.`discounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `discountcol` VARCHAR(255) NULL,
  `code` VARCHAR(255) NULL,
  `percentage` INT NULL,
  `use_times` INT NULL,
  `count_times` INT NULL,
  `discount_date` TIMESTAMP NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_discounts_users1_idx` (`client_id` ASC) VISIBLE,
  CONSTRAINT `fk_discounts_users1`
    FOREIGN KEY (`client_id`)
    REFERENCES `spruce_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spruce_db`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spruce_db`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `category_date` TIMESTAMP NULL,
  `seller_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_categories_users1_idx` (`seller_id` ASC) VISIBLE,
  CONSTRAINT `fk_categories_users1`
    FOREIGN KEY (`seller_id`)
    REFERENCES `spruce_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spruce_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spruce_db`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL,
  `price` VARCHAR(255) NULL,
  `discount_price` VARCHAR(255) NULL,
  `views` INT NULL,
  `picture_img` VARCHAR(255) NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_categories1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `spruce_db`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spruce_db`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spruce_db`.`messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `message` VARCHAR(255) NOT NULL,
  `message_date` TIMESTAMP NULL,
  `sender_id` INT NOT NULL,
  `receiver_id` INT NOT NULL,
  INDEX `fk_messages_users2_idx` (`receiver_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_messages_users1`
    FOREIGN KEY (`sender_id`)
    REFERENCES `spruce_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_messages_users2`
    FOREIGN KEY (`receiver_id`)
    REFERENCES `spruce_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spruce_db`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spruce_db`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_date` TIMESTAMP NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_users1_idx` (`client_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`client_id`)
    REFERENCES `spruce_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spruce_db`.`orders_has_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spruce_db`.`orders_has_products` (
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`order_id`, `product_id`),
  INDEX `fk_orders_has_products_products1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_orders_has_products_orders_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_has_products_orders`
    FOREIGN KEY (`order_id`)
    REFERENCES `spruce_db`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_has_products_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `spruce_db`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spruce_db`.`ads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spruce_db`.`ads` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `picture_url` VARCHAR(255) NULL,
  `link` VARCHAR(255) NULL,
  `seller_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ads_users1_idx` (`seller_id` ASC) VISIBLE,
  CONSTRAINT `fk_ads_users1`
    FOREIGN KEY (`seller_id`)
    REFERENCES `spruce_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spruce_db`.`favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spruce_db`.`favorites` (
  `product_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  `fav_date` TIMESTAMP NULL,
  PRIMARY KEY (`product_id`, `client_id`),
  INDEX `fk_products_has_users_users1_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_products_has_users_products1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_has_users_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `spruce_db`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_users_users1`
    FOREIGN KEY (`client_id`)
    REFERENCES `spruce_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spruce_db`.`wishlists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spruce_db`.`wishlists` (
  `wish_date` TIMESTAMP NULL,
  `product_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `client_id`),
  INDEX `fk_products_has_users_users2_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_products_has_users_products2_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_has_users_products2`
    FOREIGN KEY (`product_id`)
    REFERENCES `spruce_db`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_users_users2`
    FOREIGN KEY (`client_id`)
    REFERENCES `spruce_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spruce_db`.`vouchers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spruce_db`.`vouchers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NULL,
  `amount` INT NULL,
  `mail` VARCHAR(255) NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vouchers_users1_idx` (`client_id` ASC) VISIBLE,
  CONSTRAINT `fk_vouchers_users1`
    FOREIGN KEY (`client_id`)
    REFERENCES `spruce_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
