-- MySQL Script generated by MySQL Workbench
-- Wed Sep 21 07:24:18 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema spruce_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema spruce_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spruce_db` DEFAULT CHARACTER SET utf8 ;
USE `spruce_db` ;

-- -----------------------------------------------------
-- Table `spruce_db`.`user_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spruce_db`.`user_types` (
  `id` INT NOT NULL,
  `role` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spruce_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spruce_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `birthday` DATE NULL,
  `password` VARCHAR(255) NULL,
  `join_date` VARCHAR(255) NULL,
  `is_ban` TINYINT NULL,
  `profile_img` VARCHAR(255) NULL,
  `user_types_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_user_types1_idx` (`user_types_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_user_types1`
    FOREIGN KEY (`user_types_id`)
    REFERENCES `spruce_db`.`user_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spruce_db`.`discounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spruce_db`.`discounts` (
  `id` INT NOT NULL,
  `discountcol` VARCHAR(255) NULL,
  `code` VARCHAR(255) NULL,
  `percentage` INT NULL,
  `use_times` INT NULL,
  `count_times` INT NULL,
  `discount_date` DATETIME NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_discounts_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_discounts_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `spruce_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spruce_db`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spruce_db`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `category_date` DATETIME NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_categories_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_categories_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `spruce_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spruce_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spruce_db`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL,
  `price` VARCHAR(255) NULL,
  `discount_price` VARCHAR(255) NULL,
  `views` INT NULL,
  `picture_img` VARCHAR(255) NULL,
  `categories_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_categories1_idx` (`categories_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `spruce_db`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spruce_db`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spruce_db`.`messages` (
  `message` VARCHAR(255) NOT NULL,
  `message_date` DATETIME NULL,
  `sender_id` INT NOT NULL,
  `receiver_id` INT NOT NULL,
  PRIMARY KEY (`sender_id`, `receiver_id`),
  INDEX `fk_messages_users2_idx` (`receiver_id` ASC) VISIBLE,
  CONSTRAINT `fk_messages_users1`
    FOREIGN KEY (`sender_id`)
    REFERENCES `spruce_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_messages_users2`
    FOREIGN KEY (`receiver_id`)
    REFERENCES `spruce_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spruce_db`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spruce_db`.`orders` (
  `id` INT NOT NULL,
  `order_date` DATETIME NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `spruce_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spruce_db`.`orders_has_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spruce_db`.`orders_has_products` (
  `orders_id` INT NOT NULL,
  `products_id` INT NOT NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`orders_id`, `products_id`),
  INDEX `fk_orders_has_products_products1_idx` (`products_id` ASC) VISIBLE,
  INDEX `fk_orders_has_products_orders_idx` (`orders_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_has_products_orders`
    FOREIGN KEY (`orders_id`)
    REFERENCES `spruce_db`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_has_products_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `spruce_db`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spruce_db`.`ads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spruce_db`.`ads` (
  `id` INT NOT NULL,
  `picture_url` VARCHAR(255) NULL,
  `link` VARCHAR(255) NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ads_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_ads_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `spruce_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spruce_db`.`favorities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spruce_db`.`favorities` (
  `products_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `fav_date` DATE NULL,
  PRIMARY KEY (`products_id`, `users_id`),
  INDEX `fk_products_has_users_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_products_has_users_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_has_users_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `spruce_db`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_users_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `spruce_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spruce_db`.`wishlists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spruce_db`.`wishlists` (
  `wish_date` DATE NULL,
  `products_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`products_id`, `users_id`),
  INDEX `fk_products_has_users_users2_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_products_has_users_products2_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_has_users_products2`
    FOREIGN KEY (`products_id`)
    REFERENCES `spruce_db`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_users_users2`
    FOREIGN KEY (`users_id`)
    REFERENCES `spruce_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spruce_db`.`vouchers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spruce_db`.`vouchers` (
  `id` INT NOT NULL,
  `code` VARCHAR(255) NULL,
  `amount` INT NULL,
  `mail` VARCHAR(255) NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vouchers_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_vouchers_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `spruce_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
